### PR TITLE
Add Theme name

### PR DESCRIPTION
**Pull request by Andrew1Medvedev**
This PR includes `LanguageConfiguration` and `CodeSnippets` in the grammar definition objects.

### CODE REVIEW

**Comment by danipen** [comment]
@Andrew1Medvedev thanks for the contribution. I made a couple of changes. Please take a look and let me know if those changes are ok for you.

Basically, I wanted to include the language configuration and the code snippets in the GrammarDefinitions, and the Language objects.

I also added unit tests for the new functionality.

**Review by danipen — APPROVED** [review]
LGTM

**Comment by Andrew1Medvedev** [comment]
Hi Daniel,

Could you please explain how GetGrammarDefinitionByName can be used?
As I see it does not take into account case sensitivity.
For example:
  SupportedGrammars: "CSharp"
While Language.ID: "csharp"

Regards,
Andrew

**Comment by danipen** [comment]
Well in fact it's not used... Just exposed just in case. If you don't need it we can remove.

**Comment by danipen** [comment]
Basically the grammar name is the storage name (the name of the folder the grammar package is located)... 
So for example in the case of markdown the grammar name is `markdownbasics` ... (the language name is `markdown`)

A little bit confusing maybe ... So if that API is not needed for you let's remove.

Most of use cases I guess will be get the lang/grammar from the extension or from the scope name...

**Comment by Andrew1Medvedev** [comment]
Hi Daniel,

All these changes are ok for me.

Regards,
Andrew

**Comment by danipen** [comment]
Great so I'll remove that API and will merge this PR into master and will generate a new nuget.

**Comment by danipen** [comment]
@Andrew1Medvedev a new version of TextMateSharp is available in nuget, including this PR: https://www.nuget.org/packages/TextMateSharp/1.0.54

Thanks for the contribution! 🙏

**Pull request merged**
